### ISSUE TITLE
2.1.50 released

### ISSUE THREAD

**Issue by itsdomme** [Quip13/No-Distractions-Full-Screen#41]
Since the new version is finally released, would it be possible, that anybody updates the addon? That would be amazing 🥇

**Comment by mobedoor** [comment]
Potential fix [here](https://github.com/ccz-2/No-Distractions-Full-Screen/issues/39#issuecomment-1103726683)

**Comment by omega3** [comment]
On Linux 2.1.50 anki-2.1.50-linux-qt5.tar.zst
```
When loading '⁨No-Distractions-Full-Screen-master⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 244, in loadAddons
  File "/home/user/.local/share/Anki2/addons21/No-Distractions-Full-Screen-master/__init__.py", line 623, in <module>
    addon_view_menu = getMenu(mw, "&View")
  File "/home/user/.local/share/Anki2/addons21/No-Distractions-Full-Screen-master/toolbar.py", line 12, in getMenu
    menu = a.menu()
AttributeError: 'QAction' object has no attribute 'menu'
```

**Comment by itsdomme** [comment]
Same message at Win10 2.1.50 Qt6, but it's working :D

**Comment by mobedoor** [comment]
@omega3 I'm on Qt6 if that helps. I updated the release. See if that helps

**Comment by omega3** [comment]
@mobedoor [mobedoor](https://github.com/mobedoor)
Thank you very much. It even removed [issue 42](https://github.com/ccz-2/No-Distractions-Full-Screen/issues/42) that I reported. 
Is it possible for you to introduce these changes to 2.1.49 for linux which is still current stable. There are so many other errors for other add-ons that I am forced to still use 2.1.49.
For 2.1.49 I used [this one](https://github.com/rwmpelstilzchen/No-Distractions-Full-Screen) fork but it doesn't cover issue 42.

**Comment by itsdomme** [comment]
> @omega3 I'm on Qt6 if that helps. I updated the release. See if that helps

Yes it's working! Thanks a lot, that's amazing now
